### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TNWanderer** [Fuzss/netherchested#10]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

NetherChested-v6.0.0-1.19.4

### Notes (Required)

Have a room with 30+ nether chests in it extreme drop in FPS.  Most likely due to fire animation.  Possible fix to add version without flame animation

**Comment by Fuzss** [comment]
I made some changes to this in the 1.20.1 versions: The chest only produces 25% as many particles as before, and in case you really want a lot and they start producing lag you can waterlog them and no particles will appear. Won't backport to 1.19.4, no time to support that anymore now that 1.20 is out.
