### ISSUE TITLE
[Bug/Mod Conflict]: This mod overwrites another chest mod with the same name "Nether Chest"

### ISSUE THREAD

**Issue by Allifreyr** [Fuzss/netherchested#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

The mod overwrites another chest mods with the same name.

The other mod in question is here on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/nether-chest-fabric) and [GitHub](https://github.com/Kir-Antipov/nether-chest) by [Kir-Antipov](https://github.com/Kir-Antipov)

The other mod is different in the sense that it adds a new chest type that works similar to the ender chest but it's not private per person and has a slot to take items to create unique "channels". Super useful to trade and transfer items. A cloud storage solution!

The problem is that all of my "nether chests" by the other mod got replaced by this mod and all of the contents are gone from them. Thankfully I had a backup, but I can confirm that even if you remove this one. The contents from every single [Nether Chest](https://github.com/Kir-Antipov/nether-chest) are gone after relaunching the server (Backup saved the day).

Just wanted to let you know 😄

**Comment by Fuzss** [comment]
Thanks, I renamed my mod to "Nether Chested" in the latest version. You will want to save all items stored in nether chests before updating since the chests will unfortunately vanish.

**Comment by Allifreyr** [comment]
Thanks for this! Happy that they both work together now 😄
