### ISSUE TITLE
[Suggestion]: let me change the middle item. I

### ISSUE THREAD

**Issue by Jonestastic** [Fuzss/netherchested#23]
### Mod Loader (Optional)

Forge

### Suggestion (Required)

[Suggestion]: let me change the middle item. I’m just not going to use this mod anymore it takes to much effort it’s a huge trade off for little benefit

**Comment by Fuzss** [comment]
Recipes are controlled via data packs. You can make your own recipe if the nether star is too expensive for you.

**Comment by Jonestastic** [comment]
do you know where it is found in better mc 4?
