### ISSUE TITLE
[Crash]: Don't work with Create Chute

### ISSUE THREAD

**Issue by YumatanGames** [Fuzss/netherchested#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.2

### Notes (Required)

Install a create chute pulling items into it
World crashes instantly until you remove Nether Chest from the game.

### Crash Report (Required)

https://paste.ee/p/U1QJJ

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.3.
