### ISSUE TITLE
[Crash]: Exception in server tick loop

### ISSUE THREAD

**Issue by TheeFlyingPenguin** [Fuzss/netherchested#9]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20

### Mod Version (Required)

v.7.0.0

### Notes (Required)

when i want to open the chest , the server shuts down 

### Crash Report (Required)

https://gist.github.com/TheeFlyingPenguin/7f5d8194839d32f440492985df363437

### latest.log (Optional)

https://gist.github.com/TheeFlyingPenguin/e3b998dfd3ff017d037ec882a9310792

**Comment by Fuzss** [comment]
Thank you! Fixed in v7.0.1.
